In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import yfinance as yf

In [ ]:
START_DATE = "2010-01-01"
END_DATE = "2024-12-31"
N = 50
WINDOW = 60

sp500_hist = pd.read_csv("sp500_historical.csv")
sp500_2009 = sp500_hist[
    sp500_hist["date"] == "2009-12-31"
]
sp500_2009["ticker"]

5501      XOM
5502     MSFT
5503    AAPL*
5504      JNJ
5505       PG
        ...
5996     NOVL
5997      NYT
5998      MDP
5999    EKDKQ
6000      TIE
Name: ticker, Length: 500, dtype: object

In [11]:
universe_50 = (
    sp500_2009
    .sort_values("weight", ascending=False)
    .head(54)
    .copy()
)
display(universe_50[["rank", "ticker", "name", "sector", "weight"]].head())
print("Número de acciones:", len(universe_50))
print("Número de sectores:", universe_50["sector"].nunique())
display(universe_50["sector"].value_counts())

      rank ticker               name                  sector    weight
5501   1.0    XOM   EXXON MOBIL CORP                  Energy  3.253742
5502   2.0   MSFT     MICROSOFT CORP  Information Technology  2.367365
5503   3.0  AAPL*          APPLE INC  Information Technology  1.908934
5504   4.0    JNJ  JOHNSON & JOHNSON             Health Care  1.786239
5505   5.0     PG   PROCTER & GAMBLE        Consumer Staples  1.780519

Número de acciones: 54
Número de sectores: 9

sector
Information Technology        10
Consumer Staples               9
Health Care                    8
Financials                     8
Consumer Discretionary         6
Energy                         5
Industrials                    5
Telecommunication Services     2
Materials                      1
Name: count, dtype: int64

In [12]:
ticker_mapping = {"AEC1": "AXP", "0R01": "C", "GEC": "GE", "SLBA": "SLB", "UTX": "RTX", "VISA": "V"}

universe_50["ticker_yf"] = (universe_50["ticker"].str.replace("*", "", regex=False).str.strip().replace(ticker_mapping))
universe_50 = universe_50[(universe_50["ticker_yf"] != "KFT") & (universe_50["ticker_yf"] != "MON") & (universe_50["ticker_yf"] != "INCO") & (universe_50["ticker_yf"] != "QCI")].copy()
display(universe_50.head())

,date,rank,ticker,name,sector,weight,ticker_yf
5501,2009-12-31,1.0,XOM,EXXON MOBIL CORP,Energy,3.253742,XOM
5502,2009-12-31,2.0,MSFT,MICROSOFT CORP,Information Technology,2.367365,MSFT
5503,2009-12-31,3.0,AAPL*,APPLE INC,Information Technology,1.908934,AAPL
5504,2009-12-31,4.0,JNJ,JOHNSON & JOHNSON,Health Care,1.786239,JNJ
5505,2009-12-31,5.0,PG,PROCTER & GAMBLE,Consumer Staples,1.780519,PG

In [13]:
special_tickers = universe_50[
    ~universe_50["ticker"].str.match(r"^[A-Z]+$")
]

display(
    special_tickers[
        ["rank", "ticker", "ticker_yf", "name"]
    ]
)

      rank ticker ticker_yf              name
5503   3.0  AAPL*      AAPL         APPLE INC
5514  14.0   WFC*       WFC       WELLS FARGO
5533  33.0   0R01         C     CITIGROUP INC
5540  40.0   AEC1       AXP  AMERICAN EXPRESS

In [15]:
universe_50.to_csv("universe_50_2009.csv", index=False)